---
title: "STAT/MATH 495: Problem Set 10"
author: "Sarah Teichman"
date: "2017-11-28"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    collapsed: false
    smooth_scroll: false
    df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width=8, fig.height=4.5, message=FALSE, warning = FALSE)
```



# Collaboration

Please indicate who you collaborated with on this assignment: 



# Setup

```{r}
library(tidyverse)
library(broom)
library(glmnet)
library(Metrics)
```


#Loading Data

```{r}
train <- read_csv("data/train.csv")
test <- read_csv("data/test.csv")
sample_submission <- read_csv("data/sample_submission.csv")

# Only use 150 observations to train model!
set.seed(76)
train <- train %>% 
  mutate(log_price_doc = log(price_doc)) %>% 
  sample_n(150)

# Need "dummy" outcome variable to make model.matrix() code below work
test <- test %>% 
  mutate(log_price_doc=1) 

# Model formula
model_formula <- as.formula("log_price_doc ~ full_sq + area_m + raion_popul + green_zone_part + indust_part + children_preschool + preschool_education_centers_raion + children_school + school_education_centers_raion + school_education_centers_top_20_raion + healthcare_centers_raion + university_top_20_raion + sport_objects_raion + additional_education_raion + culture_objects_top_25 + culture_objects_top_25_raion + shopping_centers_raion + office_raion + thermal_power_plant_raion + incineration_raion + oil_chemistry_raion + radiation_raion + railroad_terminal_raion + big_market_raion + nuclear_reactor_raion + detention_facility_raion + full_all + male_f + female_f + young_all + young_male + young_female + work_all + work_male + work_female + ekder_all + ekder_male + ekder_female + ID_metro + metro_min_avto + metro_km_avto + kindergarten_km + school_km + park_km + green_zone_km + industrial_km + water_treatment_km + cemetery_km + incineration_km + railroad_station_avto_km + railroad_station_avto_min + ID_railroad_station_avto + public_transport_station_km + public_transport_station_min_walk + water_km + water_1line + mkad_km + ttk_km + sadovoe_km + bulvar_ring_km + kremlin_km + big_road1_km + ID_big_road1 + big_road1_1line + big_road2_km + ID_big_road2 + railroad_km + railroad_1line + zd_vokzaly_avto_km + ID_railroad_terminal + bus_terminal_avto_km + ID_bus_terminal + oil_chemistry_km + nuclear_reactor_km + radiation_km + power_transmission_line_km + thermal_power_plant_km + ts_km + big_market_km + market_shop_km + fitness_km + swim_pool_km + ice_rink_km + stadium_km + basketball_km + hospice_morgue_km + detention_facility_km + public_healthcare_km + university_km + workplaces_km + shopping_centers_km + office_km + additional_education_km + preschool_km + big_church_km + church_synagogue_km + mosque_km + theater_km + museum_km + exhibition_km + catering_km + green_part_500 + prom_part_500 + office_count_500 + office_sqm_500 + trc_count_500 + trc_sqm_500") 

# Define predictor matrices
predictor_matrix_train <- model.matrix(model_formula, data = train)[, -1]
predictor_matrix_test <- model.matrix(model_formula, data = test)[, -1]
```

# Exploratory data analysis

```{r}
ggplot(train,aes(x=price_doc)) +
  geom_histogram() +
  scale_x_log10() + 
  labs(x="Price (in roubles)", title="Distribution of prices")
```

# Model creation and selection

```{r}
#fit full lm model, fit to train and test sets
train_full <- lm(model_formula, data = train)
train_predict <- predict(train_full)
test_predict <- predict(train_full, newdata=test)
```

```{r}
#set lambda values
lambda_inputs <- 10^seq(-2, 10, length = 100)
#create lasso model
train_lasso <- cv.glmnet(x=predictor_matrix_train, y=train$log_price_doc, alpha = 1, lambda = lambda_inputs)
lambda_star <- train_lasso$lambda.min
lambda_star_1SE <- train_lasso$lambda.1se
plot(train_lasso)
abline(v=log(lambda_star), col="red")
abline(v=log(lambda_star_1SE), col="blue")
#fit lasso model to train and test sets
train_predict_lasso <- predict(train_lasso, newx=predictor_matrix_train, s=lambda_star_1SE) %>% 
  as.vector()
test_predict_lasso <- predict(train_lasso, newx=predictor_matrix_test, s=lambda_star_1SE) %>%
  as.vector()
```

```{r}
test_predict <- exp(test_predict)
test_predict_lasso <- exp(test_predict_lasso)
train_predict <- exp(train_predict)
train_predict_lasso <- exp(train_predict_lasso)
submission_full <- data.frame(test$id, test_predict)
submission_lasso <- data.frame(test$id, test_predict_lasso)
names(submission_full) <- c("Id", "price_doc")
names(submission_lasso) <- c("Id", "price_doc")
write.csv(submission_full, "submission_full.csv", row.names=FALSE)
write.csv(submission_lasso, "submission_lasso.csv", row.names=FALSE)
```

```{r}
rmsle(train$price_doc,train_predict)
rmsle(train$price_doc,train_predict_lasso)
```

# Scoreboard

Using the "scoring mechanism" for the Russian Housing Kaggle competition, fill
in these cells:


Method                | Training Score  | Kaggle Score
--------------------- | -------------   | -------------
lm                    |  0.2534         |  2.6341
LASSO crossvalidated  |  0.5172         |  0.4258
